### ISSUE TITLE
Error message returning while trying to run LKH in command line.

### ISSUE THREAD

**Issue by joeymitchll** [superpermutators/superperm#17]
After creating the directories to run LKH, the error message 
`*** Error ***
Cannot open PARAMETER_FILE: "lkh/par/5.par"`
I've reinstalled the files a couple of times with no success, and am able to return data running the parameter files stated in the User Guide, but I can't seem to have any luck getting past this point.

**Comment by robinhouston** [comment]
Strange. I’ve never seen that. Thanks for reporting.

What OS are you using? Can you post a screenshot or transcript of the command you ran?

**Comment by joeymitchll** [comment]
Sure thing.
MacOS Mojave Version 10.14.3

Transcript:
` 501  cd LKH-2.0.7
  502  make
  503  cp ./LKH /usr/local/bin/
  504  LKH lkh/par/5.par
`

**Comment by robinhouston** [comment]
Is it just that you’re still in the `LKH-2.0.7` directory at the point where you try to run it? What happens if you `cd` back to the superperm directory first?

**Comment by joeymitchll** [comment]
It returns the same error message in both directories.

**Comment by robinhouston** [comment]
Okay, that’s weird! So, if you run `cat lkh/par/5.par` then it works, but if you run `LKH lkh/par/5.par` then it doesn’t?

What if you pass the absolute path of the `.par` file to LKH? Surely that will work, at least.

**Comment by joeymitchll** [comment]
Running a cat command returns that there is no such directory, should I wipe the files and re-curl it to get the correct directories.

**Comment by robinhouston** [comment]
If you have a checkout of this repository, there is an `lkh` directory which contains these parameter files. If not, you should clone the repository by using the green “Clone or download” button or running the command

```
git clone https://github.com/superpermutators/superperm.git
```

**Comment by joeymitchll** [comment]
I uninstalled all files and re-curled, and made sure that the superperm folder was there and everything is working fine now! Thanks for the help.

**Comment by robinhouston** [comment]
Glad to hear it!
