### ISSUE TITLE
Strip line ending on superperm hashes

### ISSUE THREAD

**Issue by tahg** [superpermutators/superperm#6]
In order to more universally handle instances, I would suggest that they be stripped to just the string of digits and not have a terminating line ending of any sort. (And then re-indexed with the new hashes)

EDIT Ended up just writing code to auto output a correctly formatted file with a proper name, but it's an interesting consideration regardless.

**Comment by robinhouston** [comment]
Agree we should be consistent. I think my own preference would be to always (rather than never) have a terminating LF, because it makes the files slightly easier to handle using standard Unixish tools.

**Comment by robinhouston** [comment]
(But the hash should probably be computed without the LF.)
